# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Currency(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, description=None, id=None, label=None, type=None, using_country=None):  # noqa: E501
        """Currency - a model defined in OpenAPI

        :param description: The description of this Currency.  # noqa: E501
        :type description: List[str]
        :param id: The id of this Currency.  # noqa: E501
        :type id: str
        :param label: The label of this Currency.  # noqa: E501
        :type label: List[str]
        :param type: The type of this Currency.  # noqa: E501
        :type type: List[str]
        :param using_country: The using_country of this Currency.  # noqa: E501
        :type using_country: List[object]
        """


        self.openapi_types = {
            'description': List[str],
            'id': str,
            'label': List[str],
            'type': List[str],
            'using_country': List[object]
        }

        self.attribute_map = {
            'description': 'description',
            'id': 'id',
            'label': 'label',
            'type': 'type',
            'using_country': 'usingCountry'
        }

        self._description = description
        self._id = id
        self._label = label
        self._type = type
        self._using_country = using_country

    @classmethod
    def from_dict(cls, dikt) -> 'Currency':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Currency of this Currency.  # noqa: E501
        :rtype: Currency
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self):
        """Gets the description of this Currency.

        small description  # noqa: E501

        :return: The description of this Currency.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Currency.

        small description  # noqa: E501

        :param description: The description of this Currency.
        :type description: List[str]
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this Currency.

        identifier  # noqa: E501

        :return: The id of this Currency.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Currency.

        identifier  # noqa: E501

        :param id: The id of this Currency.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this Currency.

        short description of the resource  # noqa: E501

        :return: The label of this Currency.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Currency.

        short description of the resource  # noqa: E501

        :param label: The label of this Currency.
        :type label: List[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this Currency.

        type of the resource  # noqa: E501

        :return: The type of this Currency.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Currency.

        type of the resource  # noqa: E501

        :param type: The type of this Currency.
        :type type: List[str]
        """

        self._type = type

    @property
    def using_country(self):
        """Gets the using_country of this Currency.

        Description not available  # noqa: E501

        :return: The using_country of this Currency.
        :rtype: List[object]
        """
        return self._using_country

    @using_country.setter
    def using_country(self, using_country):
        """Sets the using_country of this Currency.

        Description not available  # noqa: E501

        :param using_country: The using_country of this Currency.
        :type using_country: List[object]
        """

        self._using_country = using_country
