# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Galaxy(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mean_radius=None, cluster=None, orbital_period=None, surface_area=None, orbital_eccentricity=None, mass=None, description=None, type=None, max_absolute_magnitude=None, mean_temperature=None, constellation=None, von_klitzing_constant=None, maximum_temperature=None, temperature=None, definition=None, id=None, periapsis=None, absolute_magnitude=None, density=None, notable_features=None, average_speed=None, label=None, apoapsis=None, volume=None, messier_name=None, max_apparent_magnitude=None, explorer=None, minimum_temperature=None, ngc_name=None):  # noqa: E501
        """Galaxy - a model defined in OpenAPI

        :param mean_radius: The mean_radius of this Galaxy.  # noqa: E501
        :type mean_radius: List[object]
        :param cluster: The cluster of this Galaxy.  # noqa: E501
        :type cluster: List[object]
        :param orbital_period: The orbital_period of this Galaxy.  # noqa: E501
        :type orbital_period: List[object]
        :param surface_area: The surface_area of this Galaxy.  # noqa: E501
        :type surface_area: List[object]
        :param orbital_eccentricity: The orbital_eccentricity of this Galaxy.  # noqa: E501
        :type orbital_eccentricity: List[float]
        :param mass: The mass of this Galaxy.  # noqa: E501
        :type mass: List[object]
        :param description: The description of this Galaxy.  # noqa: E501
        :type description: List[str]
        :param type: The type of this Galaxy.  # noqa: E501
        :type type: List[str]
        :param max_absolute_magnitude: The max_absolute_magnitude of this Galaxy.  # noqa: E501
        :type max_absolute_magnitude: List[float]
        :param mean_temperature: The mean_temperature of this Galaxy.  # noqa: E501
        :type mean_temperature: List[object]
        :param constellation: The constellation of this Galaxy.  # noqa: E501
        :type constellation: List[object]
        :param von_klitzing_constant: The von_klitzing_constant of this Galaxy.  # noqa: E501
        :type von_klitzing_constant: List[float]
        :param maximum_temperature: The maximum_temperature of this Galaxy.  # noqa: E501
        :type maximum_temperature: List[object]
        :param temperature: The temperature of this Galaxy.  # noqa: E501
        :type temperature: List[object]
        :param definition: The definition of this Galaxy.  # noqa: E501
        :type definition: List[str]
        :param id: The id of this Galaxy.  # noqa: E501
        :type id: str
        :param periapsis: The periapsis of this Galaxy.  # noqa: E501
        :type periapsis: List[object]
        :param absolute_magnitude: The absolute_magnitude of this Galaxy.  # noqa: E501
        :type absolute_magnitude: List[float]
        :param density: The density of this Galaxy.  # noqa: E501
        :type density: List[object]
        :param notable_features: The notable_features of this Galaxy.  # noqa: E501
        :type notable_features: List[str]
        :param average_speed: The average_speed of this Galaxy.  # noqa: E501
        :type average_speed: List[object]
        :param label: The label of this Galaxy.  # noqa: E501
        :type label: List[str]
        :param apoapsis: The apoapsis of this Galaxy.  # noqa: E501
        :type apoapsis: List[object]
        :param volume: The volume of this Galaxy.  # noqa: E501
        :type volume: List[object]
        :param messier_name: The messier_name of this Galaxy.  # noqa: E501
        :type messier_name: List[str]
        :param max_apparent_magnitude: The max_apparent_magnitude of this Galaxy.  # noqa: E501
        :type max_apparent_magnitude: List[float]
        :param explorer: The explorer of this Galaxy.  # noqa: E501
        :type explorer: List[object]
        :param minimum_temperature: The minimum_temperature of this Galaxy.  # noqa: E501
        :type minimum_temperature: List[object]
        :param ngc_name: The ngc_name of this Galaxy.  # noqa: E501
        :type ngc_name: List[str]
        """


        self.openapi_types = {
            'mean_radius': List[object],
            'cluster': List[object],
            'orbital_period': List[object],
            'surface_area': List[object],
            'orbital_eccentricity': List[float],
            'mass': List[object],
            'description': List[str],
            'type': List[str],
            'max_absolute_magnitude': List[float],
            'mean_temperature': List[object],
            'constellation': List[object],
            'von_klitzing_constant': List[float],
            'maximum_temperature': List[object],
            'temperature': List[object],
            'definition': List[str],
            'id': str,
            'periapsis': List[object],
            'absolute_magnitude': List[float],
            'density': List[object],
            'notable_features': List[str],
            'average_speed': List[object],
            'label': List[str],
            'apoapsis': List[object],
            'volume': List[object],
            'messier_name': List[str],
            'max_apparent_magnitude': List[float],
            'explorer': List[object],
            'minimum_temperature': List[object],
            'ngc_name': List[str]
        }

        self.attribute_map = {
            'mean_radius': 'meanRadius',
            'cluster': 'cluster',
            'orbital_period': 'orbitalPeriod',
            'surface_area': 'surfaceArea',
            'orbital_eccentricity': 'orbitalEccentricity',
            'mass': 'mass',
            'description': 'description',
            'type': 'type',
            'max_absolute_magnitude': 'maxAbsoluteMagnitude',
            'mean_temperature': 'meanTemperature',
            'constellation': 'constellation',
            'von_klitzing_constant': 'vonKlitzingConstant',
            'maximum_temperature': 'maximumTemperature',
            'temperature': 'temperature',
            'definition': 'definition',
            'id': 'id',
            'periapsis': 'periapsis',
            'absolute_magnitude': 'absoluteMagnitude',
            'density': 'density',
            'notable_features': 'notableFeatures',
            'average_speed': 'averageSpeed',
            'label': 'label',
            'apoapsis': 'apoapsis',
            'volume': 'volume',
            'messier_name': 'messierName',
            'max_apparent_magnitude': 'maxApparentMagnitude',
            'explorer': 'explorer',
            'minimum_temperature': 'minimumTemperature',
            'ngc_name': 'ngcName'
        }

        self._mean_radius = mean_radius
        self._cluster = cluster
        self._orbital_period = orbital_period
        self._surface_area = surface_area
        self._orbital_eccentricity = orbital_eccentricity
        self._mass = mass
        self._description = description
        self._type = type
        self._max_absolute_magnitude = max_absolute_magnitude
        self._mean_temperature = mean_temperature
        self._constellation = constellation
        self._von_klitzing_constant = von_klitzing_constant
        self._maximum_temperature = maximum_temperature
        self._temperature = temperature
        self._definition = definition
        self._id = id
        self._periapsis = periapsis
        self._absolute_magnitude = absolute_magnitude
        self._density = density
        self._notable_features = notable_features
        self._average_speed = average_speed
        self._label = label
        self._apoapsis = apoapsis
        self._volume = volume
        self._messier_name = messier_name
        self._max_apparent_magnitude = max_apparent_magnitude
        self._explorer = explorer
        self._minimum_temperature = minimum_temperature
        self._ngc_name = ngc_name

    @classmethod
    def from_dict(cls, dikt) -> 'Galaxy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Galaxy of this Galaxy.  # noqa: E501
        :rtype: Galaxy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mean_radius(self):
        """Gets the mean_radius of this Galaxy.

        Description not available  # noqa: E501

        :return: The mean_radius of this Galaxy.
        :rtype: List[object]
        """
        return self._mean_radius

    @mean_radius.setter
    def mean_radius(self, mean_radius):
        """Sets the mean_radius of this Galaxy.

        Description not available  # noqa: E501

        :param mean_radius: The mean_radius of this Galaxy.
        :type mean_radius: List[object]
        """

        self._mean_radius = mean_radius

    @property
    def cluster(self):
        """Gets the cluster of this Galaxy.

        Description not available  # noqa: E501

        :return: The cluster of this Galaxy.
        :rtype: List[object]
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this Galaxy.

        Description not available  # noqa: E501

        :param cluster: The cluster of this Galaxy.
        :type cluster: List[object]
        """

        self._cluster = cluster

    @property
    def orbital_period(self):
        """Gets the orbital_period of this Galaxy.

        Description not available  # noqa: E501

        :return: The orbital_period of this Galaxy.
        :rtype: List[object]
        """
        return self._orbital_period

    @orbital_period.setter
    def orbital_period(self, orbital_period):
        """Sets the orbital_period of this Galaxy.

        Description not available  # noqa: E501

        :param orbital_period: The orbital_period of this Galaxy.
        :type orbital_period: List[object]
        """

        self._orbital_period = orbital_period

    @property
    def surface_area(self):
        """Gets the surface_area of this Galaxy.

        Description not available  # noqa: E501

        :return: The surface_area of this Galaxy.
        :rtype: List[object]
        """
        return self._surface_area

    @surface_area.setter
    def surface_area(self, surface_area):
        """Sets the surface_area of this Galaxy.

        Description not available  # noqa: E501

        :param surface_area: The surface_area of this Galaxy.
        :type surface_area: List[object]
        """

        self._surface_area = surface_area

    @property
    def orbital_eccentricity(self):
        """Gets the orbital_eccentricity of this Galaxy.

        Description not available  # noqa: E501

        :return: The orbital_eccentricity of this Galaxy.
        :rtype: List[float]
        """
        return self._orbital_eccentricity

    @orbital_eccentricity.setter
    def orbital_eccentricity(self, orbital_eccentricity):
        """Sets the orbital_eccentricity of this Galaxy.

        Description not available  # noqa: E501

        :param orbital_eccentricity: The orbital_eccentricity of this Galaxy.
        :type orbital_eccentricity: List[float]
        """

        self._orbital_eccentricity = orbital_eccentricity

    @property
    def mass(self):
        """Gets the mass of this Galaxy.

        Description not available  # noqa: E501

        :return: The mass of this Galaxy.
        :rtype: List[object]
        """
        return self._mass

    @mass.setter
    def mass(self, mass):
        """Sets the mass of this Galaxy.

        Description not available  # noqa: E501

        :param mass: The mass of this Galaxy.
        :type mass: List[object]
        """

        self._mass = mass

    @property
    def description(self):
        """Gets the description of this Galaxy.

        small description  # noqa: E501

        :return: The description of this Galaxy.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Galaxy.

        small description  # noqa: E501

        :param description: The description of this Galaxy.
        :type description: List[str]
        """

        self._description = description

    @property
    def type(self):
        """Gets the type of this Galaxy.

        type of the resource  # noqa: E501

        :return: The type of this Galaxy.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Galaxy.

        type of the resource  # noqa: E501

        :param type: The type of this Galaxy.
        :type type: List[str]
        """

        self._type = type

    @property
    def max_absolute_magnitude(self):
        """Gets the max_absolute_magnitude of this Galaxy.

        Description not available  # noqa: E501

        :return: The max_absolute_magnitude of this Galaxy.
        :rtype: List[float]
        """
        return self._max_absolute_magnitude

    @max_absolute_magnitude.setter
    def max_absolute_magnitude(self, max_absolute_magnitude):
        """Sets the max_absolute_magnitude of this Galaxy.

        Description not available  # noqa: E501

        :param max_absolute_magnitude: The max_absolute_magnitude of this Galaxy.
        :type max_absolute_magnitude: List[float]
        """

        self._max_absolute_magnitude = max_absolute_magnitude

    @property
    def mean_temperature(self):
        """Gets the mean_temperature of this Galaxy.

        Description not available  # noqa: E501

        :return: The mean_temperature of this Galaxy.
        :rtype: List[object]
        """
        return self._mean_temperature

    @mean_temperature.setter
    def mean_temperature(self, mean_temperature):
        """Sets the mean_temperature of this Galaxy.

        Description not available  # noqa: E501

        :param mean_temperature: The mean_temperature of this Galaxy.
        :type mean_temperature: List[object]
        """

        self._mean_temperature = mean_temperature

    @property
    def constellation(self):
        """Gets the constellation of this Galaxy.

        Description not available  # noqa: E501

        :return: The constellation of this Galaxy.
        :rtype: List[object]
        """
        return self._constellation

    @constellation.setter
    def constellation(self, constellation):
        """Sets the constellation of this Galaxy.

        Description not available  # noqa: E501

        :param constellation: The constellation of this Galaxy.
        :type constellation: List[object]
        """

        self._constellation = constellation

    @property
    def von_klitzing_constant(self):
        """Gets the von_klitzing_constant of this Galaxy.

        Description not available  # noqa: E501

        :return: The von_klitzing_constant of this Galaxy.
        :rtype: List[float]
        """
        return self._von_klitzing_constant

    @von_klitzing_constant.setter
    def von_klitzing_constant(self, von_klitzing_constant):
        """Sets the von_klitzing_constant of this Galaxy.

        Description not available  # noqa: E501

        :param von_klitzing_constant: The von_klitzing_constant of this Galaxy.
        :type von_klitzing_constant: List[float]
        """

        self._von_klitzing_constant = von_klitzing_constant

    @property
    def maximum_temperature(self):
        """Gets the maximum_temperature of this Galaxy.

        Description not available  # noqa: E501

        :return: The maximum_temperature of this Galaxy.
        :rtype: List[object]
        """
        return self._maximum_temperature

    @maximum_temperature.setter
    def maximum_temperature(self, maximum_temperature):
        """Sets the maximum_temperature of this Galaxy.

        Description not available  # noqa: E501

        :param maximum_temperature: The maximum_temperature of this Galaxy.
        :type maximum_temperature: List[object]
        """

        self._maximum_temperature = maximum_temperature

    @property
    def temperature(self):
        """Gets the temperature of this Galaxy.

        Description not available  # noqa: E501

        :return: The temperature of this Galaxy.
        :rtype: List[object]
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this Galaxy.

        Description not available  # noqa: E501

        :param temperature: The temperature of this Galaxy.
        :type temperature: List[object]
        """

        self._temperature = temperature

    @property
    def definition(self):
        """Gets the definition of this Galaxy.

        Description not available  # noqa: E501

        :return: The definition of this Galaxy.
        :rtype: List[str]
        """
        return self._definition

    @definition.setter
    def definition(self, definition):
        """Sets the definition of this Galaxy.

        Description not available  # noqa: E501

        :param definition: The definition of this Galaxy.
        :type definition: List[str]
        """

        self._definition = definition

    @property
    def id(self):
        """Gets the id of this Galaxy.

        identifier  # noqa: E501

        :return: The id of this Galaxy.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Galaxy.

        identifier  # noqa: E501

        :param id: The id of this Galaxy.
        :type id: str
        """

        self._id = id

    @property
    def periapsis(self):
        """Gets the periapsis of this Galaxy.

        Description not available  # noqa: E501

        :return: The periapsis of this Galaxy.
        :rtype: List[object]
        """
        return self._periapsis

    @periapsis.setter
    def periapsis(self, periapsis):
        """Sets the periapsis of this Galaxy.

        Description not available  # noqa: E501

        :param periapsis: The periapsis of this Galaxy.
        :type periapsis: List[object]
        """

        self._periapsis = periapsis

    @property
    def absolute_magnitude(self):
        """Gets the absolute_magnitude of this Galaxy.

        Description not available  # noqa: E501

        :return: The absolute_magnitude of this Galaxy.
        :rtype: List[float]
        """
        return self._absolute_magnitude

    @absolute_magnitude.setter
    def absolute_magnitude(self, absolute_magnitude):
        """Sets the absolute_magnitude of this Galaxy.

        Description not available  # noqa: E501

        :param absolute_magnitude: The absolute_magnitude of this Galaxy.
        :type absolute_magnitude: List[float]
        """

        self._absolute_magnitude = absolute_magnitude

    @property
    def density(self):
        """Gets the density of this Galaxy.

        Description not available  # noqa: E501

        :return: The density of this Galaxy.
        :rtype: List[object]
        """
        return self._density

    @density.setter
    def density(self, density):
        """Sets the density of this Galaxy.

        Description not available  # noqa: E501

        :param density: The density of this Galaxy.
        :type density: List[object]
        """

        self._density = density

    @property
    def notable_features(self):
        """Gets the notable_features of this Galaxy.

        Description not available  # noqa: E501

        :return: The notable_features of this Galaxy.
        :rtype: List[str]
        """
        return self._notable_features

    @notable_features.setter
    def notable_features(self, notable_features):
        """Sets the notable_features of this Galaxy.

        Description not available  # noqa: E501

        :param notable_features: The notable_features of this Galaxy.
        :type notable_features: List[str]
        """

        self._notable_features = notable_features

    @property
    def average_speed(self):
        """Gets the average_speed of this Galaxy.

        The average speed of a thing.  # noqa: E501

        :return: The average_speed of this Galaxy.
        :rtype: List[object]
        """
        return self._average_speed

    @average_speed.setter
    def average_speed(self, average_speed):
        """Sets the average_speed of this Galaxy.

        The average speed of a thing.  # noqa: E501

        :param average_speed: The average_speed of this Galaxy.
        :type average_speed: List[object]
        """

        self._average_speed = average_speed

    @property
    def label(self):
        """Gets the label of this Galaxy.

        short description of the resource  # noqa: E501

        :return: The label of this Galaxy.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Galaxy.

        short description of the resource  # noqa: E501

        :param label: The label of this Galaxy.
        :type label: List[str]
        """

        self._label = label

    @property
    def apoapsis(self):
        """Gets the apoapsis of this Galaxy.

        Description not available  # noqa: E501

        :return: The apoapsis of this Galaxy.
        :rtype: List[object]
        """
        return self._apoapsis

    @apoapsis.setter
    def apoapsis(self, apoapsis):
        """Sets the apoapsis of this Galaxy.

        Description not available  # noqa: E501

        :param apoapsis: The apoapsis of this Galaxy.
        :type apoapsis: List[object]
        """

        self._apoapsis = apoapsis

    @property
    def volume(self):
        """Gets the volume of this Galaxy.

        Description not available  # noqa: E501

        :return: The volume of this Galaxy.
        :rtype: List[object]
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this Galaxy.

        Description not available  # noqa: E501

        :param volume: The volume of this Galaxy.
        :type volume: List[object]
        """

        self._volume = volume

    @property
    def messier_name(self):
        """Gets the messier_name of this Galaxy.

        Name for Messier objects  # noqa: E501

        :return: The messier_name of this Galaxy.
        :rtype: List[str]
        """
        return self._messier_name

    @messier_name.setter
    def messier_name(self, messier_name):
        """Sets the messier_name of this Galaxy.

        Name for Messier objects  # noqa: E501

        :param messier_name: The messier_name of this Galaxy.
        :type messier_name: List[str]
        """

        self._messier_name = messier_name

    @property
    def max_apparent_magnitude(self):
        """Gets the max_apparent_magnitude of this Galaxy.

        Description not available  # noqa: E501

        :return: The max_apparent_magnitude of this Galaxy.
        :rtype: List[float]
        """
        return self._max_apparent_magnitude

    @max_apparent_magnitude.setter
    def max_apparent_magnitude(self, max_apparent_magnitude):
        """Sets the max_apparent_magnitude of this Galaxy.

        Description not available  # noqa: E501

        :param max_apparent_magnitude: The max_apparent_magnitude of this Galaxy.
        :type max_apparent_magnitude: List[float]
        """

        self._max_apparent_magnitude = max_apparent_magnitude

    @property
    def explorer(self):
        """Gets the explorer of this Galaxy.

        Description not available  # noqa: E501

        :return: The explorer of this Galaxy.
        :rtype: List[object]
        """
        return self._explorer

    @explorer.setter
    def explorer(self, explorer):
        """Sets the explorer of this Galaxy.

        Description not available  # noqa: E501

        :param explorer: The explorer of this Galaxy.
        :type explorer: List[object]
        """

        self._explorer = explorer

    @property
    def minimum_temperature(self):
        """Gets the minimum_temperature of this Galaxy.

        Description not available  # noqa: E501

        :return: The minimum_temperature of this Galaxy.
        :rtype: List[object]
        """
        return self._minimum_temperature

    @minimum_temperature.setter
    def minimum_temperature(self, minimum_temperature):
        """Sets the minimum_temperature of this Galaxy.

        Description not available  # noqa: E501

        :param minimum_temperature: The minimum_temperature of this Galaxy.
        :type minimum_temperature: List[object]
        """

        self._minimum_temperature = minimum_temperature

    @property
    def ngc_name(self):
        """Gets the ngc_name of this Galaxy.

        Name for NGC objects  # noqa: E501

        :return: The ngc_name of this Galaxy.
        :rtype: List[str]
        """
        return self._ngc_name

    @ngc_name.setter
    def ngc_name(self, ngc_name):
        """Sets the ngc_name of this Galaxy.

        Name for NGC objects  # noqa: E501

        :param ngc_name: The ngc_name of this Galaxy.
        :type ngc_name: List[str]
        """

        self._ngc_name = ngc_name
