# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Instrument(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, musicians=None, description=None, id=None, label=None, classification=None, type=None):  # noqa: E501
        """Instrument - a model defined in OpenAPI

        :param musicians: The musicians of this Instrument.  # noqa: E501
        :type musicians: List[object]
        :param description: The description of this Instrument.  # noqa: E501
        :type description: List[str]
        :param id: The id of this Instrument.  # noqa: E501
        :type id: str
        :param label: The label of this Instrument.  # noqa: E501
        :type label: List[str]
        :param classification: The classification of this Instrument.  # noqa: E501
        :type classification: List[str]
        :param type: The type of this Instrument.  # noqa: E501
        :type type: List[str]
        """


        self.openapi_types = {
            'musicians': List[object],
            'description': List[str],
            'id': str,
            'label': List[str],
            'classification': List[str],
            'type': List[str]
        }

        self.attribute_map = {
            'musicians': 'musicians',
            'description': 'description',
            'id': 'id',
            'label': 'label',
            'classification': 'classification',
            'type': 'type'
        }

        self._musicians = musicians
        self._description = description
        self._id = id
        self._label = label
        self._classification = classification
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Instrument':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Instrument of this Instrument.  # noqa: E501
        :rtype: Instrument
        """
        return util.deserialize_model(dikt, cls)

    @property
    def musicians(self):
        """Gets the musicians of this Instrument.

        Description not available  # noqa: E501

        :return: The musicians of this Instrument.
        :rtype: List[object]
        """
        return self._musicians

    @musicians.setter
    def musicians(self, musicians):
        """Sets the musicians of this Instrument.

        Description not available  # noqa: E501

        :param musicians: The musicians of this Instrument.
        :type musicians: List[object]
        """

        self._musicians = musicians

    @property
    def description(self):
        """Gets the description of this Instrument.

        small description  # noqa: E501

        :return: The description of this Instrument.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Instrument.

        small description  # noqa: E501

        :param description: The description of this Instrument.
        :type description: List[str]
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this Instrument.

        identifier  # noqa: E501

        :return: The id of this Instrument.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Instrument.

        identifier  # noqa: E501

        :param id: The id of this Instrument.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this Instrument.

        short description of the resource  # noqa: E501

        :return: The label of this Instrument.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Instrument.

        short description of the resource  # noqa: E501

        :param label: The label of this Instrument.
        :type label: List[str]
        """

        self._label = label

    @property
    def classification(self):
        """Gets the classification of this Instrument.

        Description not available  # noqa: E501

        :return: The classification of this Instrument.
        :rtype: List[str]
        """
        return self._classification

    @classification.setter
    def classification(self, classification):
        """Sets the classification of this Instrument.

        Description not available  # noqa: E501

        :param classification: The classification of this Instrument.
        :type classification: List[str]
        """

        self._classification = classification

    @property
    def type(self):
        """Gets the type of this Instrument.

        type of the resource  # noqa: E501

        :return: The type of this Instrument.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Instrument.

        type of the resource  # noqa: E501

        :param type: The type of this Instrument.
        :type type: List[str]
        """

        self._type = type
