# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Legislature(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, viaf_id=None, leader_function=None, number_of_members=None, art_patron=None, manager_season=None, secretary_general=None, number_of_locations=None, discipline=None, legislative_period_name=None, type=None, committee_in_legislature=None, revenue=None, last_election_date=None, affiliation=None, political_party_in_legislature=None, meeting_city=None, season=None, meeting_building=None, id=None, nla_id=None, chairperson=None, region_served=None, superintendent=None, formation_date=None, number_of_employees=None, election_date_leader=None, extinction_date=None, player_season=None, endowment=None, slogan=None, regional_council=None, location_city=None, number_of_volunteers=None, ideology=None, description=None, membership=None, ceo=None, house=None, formation_year=None, junior_season=None, headquarter=None, extinction_year=None, child_organisation=None, honours=None, parent_organisation=None, organisation_member=None, number_of_staff=None, product=None, hometown=None, foundation_place=None, national_selection=None, label=None, legal_form=None, political_party_of_leader=None, general_council=None, trustee=None, age=None, main_organ=None):  # noqa: E501
        """Legislature - a model defined in OpenAPI

        :param viaf_id: The viaf_id of this Legislature.  # noqa: E501
        :type viaf_id: List[str]
        :param leader_function: The leader_function of this Legislature.  # noqa: E501
        :type leader_function: List[object]
        :param number_of_members: The number_of_members of this Legislature.  # noqa: E501
        :type number_of_members: List[int]
        :param art_patron: The art_patron of this Legislature.  # noqa: E501
        :type art_patron: List[object]
        :param manager_season: The manager_season of this Legislature.  # noqa: E501
        :type manager_season: List[object]
        :param secretary_general: The secretary_general of this Legislature.  # noqa: E501
        :type secretary_general: List[object]
        :param number_of_locations: The number_of_locations of this Legislature.  # noqa: E501
        :type number_of_locations: List[int]
        :param discipline: The discipline of this Legislature.  # noqa: E501
        :type discipline: List[object]
        :param legislative_period_name: The legislative_period_name of this Legislature.  # noqa: E501
        :type legislative_period_name: List[str]
        :param type: The type of this Legislature.  # noqa: E501
        :type type: List[str]
        :param committee_in_legislature: The committee_in_legislature of this Legislature.  # noqa: E501
        :type committee_in_legislature: List[object]
        :param revenue: The revenue of this Legislature.  # noqa: E501
        :type revenue: List[float]
        :param last_election_date: The last_election_date of this Legislature.  # noqa: E501
        :type last_election_date: List[str]
        :param affiliation: The affiliation of this Legislature.  # noqa: E501
        :type affiliation: List[object]
        :param political_party_in_legislature: The political_party_in_legislature of this Legislature.  # noqa: E501
        :type political_party_in_legislature: List[object]
        :param meeting_city: The meeting_city of this Legislature.  # noqa: E501
        :type meeting_city: List[object]
        :param season: The season of this Legislature.  # noqa: E501
        :type season: List[object]
        :param meeting_building: The meeting_building of this Legislature.  # noqa: E501
        :type meeting_building: List[object]
        :param id: The id of this Legislature.  # noqa: E501
        :type id: str
        :param nla_id: The nla_id of this Legislature.  # noqa: E501
        :type nla_id: List[str]
        :param chairperson: The chairperson of this Legislature.  # noqa: E501
        :type chairperson: List[object]
        :param region_served: The region_served of this Legislature.  # noqa: E501
        :type region_served: List[object]
        :param superintendent: The superintendent of this Legislature.  # noqa: E501
        :type superintendent: List[object]
        :param formation_date: The formation_date of this Legislature.  # noqa: E501
        :type formation_date: List[str]
        :param number_of_employees: The number_of_employees of this Legislature.  # noqa: E501
        :type number_of_employees: List[int]
        :param election_date_leader: The election_date_leader of this Legislature.  # noqa: E501
        :type election_date_leader: List[str]
        :param extinction_date: The extinction_date of this Legislature.  # noqa: E501
        :type extinction_date: List[str]
        :param player_season: The player_season of this Legislature.  # noqa: E501
        :type player_season: List[object]
        :param endowment: The endowment of this Legislature.  # noqa: E501
        :type endowment: List[float]
        :param slogan: The slogan of this Legislature.  # noqa: E501
        :type slogan: List[str]
        :param regional_council: The regional_council of this Legislature.  # noqa: E501
        :type regional_council: List[object]
        :param location_city: The location_city of this Legislature.  # noqa: E501
        :type location_city: List[object]
        :param number_of_volunteers: The number_of_volunteers of this Legislature.  # noqa: E501
        :type number_of_volunteers: List[int]
        :param ideology: The ideology of this Legislature.  # noqa: E501
        :type ideology: List[object]
        :param description: The description of this Legislature.  # noqa: E501
        :type description: List[str]
        :param membership: The membership of this Legislature.  # noqa: E501
        :type membership: List[str]
        :param ceo: The ceo of this Legislature.  # noqa: E501
        :type ceo: List[object]
        :param house: The house of this Legislature.  # noqa: E501
        :type house: List[object]
        :param formation_year: The formation_year of this Legislature.  # noqa: E501
        :type formation_year: List[str]
        :param junior_season: The junior_season of this Legislature.  # noqa: E501
        :type junior_season: List[object]
        :param headquarter: The headquarter of this Legislature.  # noqa: E501
        :type headquarter: List[object]
        :param extinction_year: The extinction_year of this Legislature.  # noqa: E501
        :type extinction_year: List[str]
        :param child_organisation: The child_organisation of this Legislature.  # noqa: E501
        :type child_organisation: List[object]
        :param honours: The honours of this Legislature.  # noqa: E501
        :type honours: List[object]
        :param parent_organisation: The parent_organisation of this Legislature.  # noqa: E501
        :type parent_organisation: List[object]
        :param organisation_member: The organisation_member of this Legislature.  # noqa: E501
        :type organisation_member: List[object]
        :param number_of_staff: The number_of_staff of this Legislature.  # noqa: E501
        :type number_of_staff: List[int]
        :param product: The product of this Legislature.  # noqa: E501
        :type product: List[object]
        :param hometown: The hometown of this Legislature.  # noqa: E501
        :type hometown: List[object]
        :param foundation_place: The foundation_place of this Legislature.  # noqa: E501
        :type foundation_place: List[object]
        :param national_selection: The national_selection of this Legislature.  # noqa: E501
        :type national_selection: List[object]
        :param label: The label of this Legislature.  # noqa: E501
        :type label: List[str]
        :param legal_form: The legal_form of this Legislature.  # noqa: E501
        :type legal_form: List[object]
        :param political_party_of_leader: The political_party_of_leader of this Legislature.  # noqa: E501
        :type political_party_of_leader: List[object]
        :param general_council: The general_council of this Legislature.  # noqa: E501
        :type general_council: List[object]
        :param trustee: The trustee of this Legislature.  # noqa: E501
        :type trustee: List[object]
        :param age: The age of this Legislature.  # noqa: E501
        :type age: List[int]
        :param main_organ: The main_organ of this Legislature.  # noqa: E501
        :type main_organ: List[object]
        """


        self.openapi_types = {
            'viaf_id': List[str],
            'leader_function': List[object],
            'number_of_members': List[int],
            'art_patron': List[object],
            'manager_season': List[object],
            'secretary_general': List[object],
            'number_of_locations': List[int],
            'discipline': List[object],
            'legislative_period_name': List[str],
            'type': List[str],
            'committee_in_legislature': List[object],
            'revenue': List[float],
            'last_election_date': List[str],
            'affiliation': List[object],
            'political_party_in_legislature': List[object],
            'meeting_city': List[object],
            'season': List[object],
            'meeting_building': List[object],
            'id': str,
            'nla_id': List[str],
            'chairperson': List[object],
            'region_served': List[object],
            'superintendent': List[object],
            'formation_date': List[str],
            'number_of_employees': List[int],
            'election_date_leader': List[str],
            'extinction_date': List[str],
            'player_season': List[object],
            'endowment': List[float],
            'slogan': List[str],
            'regional_council': List[object],
            'location_city': List[object],
            'number_of_volunteers': List[int],
            'ideology': List[object],
            'description': List[str],
            'membership': List[str],
            'ceo': List[object],
            'house': List[object],
            'formation_year': List[str],
            'junior_season': List[object],
            'headquarter': List[object],
            'extinction_year': List[str],
            'child_organisation': List[object],
            'honours': List[object],
            'parent_organisation': List[object],
            'organisation_member': List[object],
            'number_of_staff': List[int],
            'product': List[object],
            'hometown': List[object],
            'foundation_place': List[object],
            'national_selection': List[object],
            'label': List[str],
            'legal_form': List[object],
            'political_party_of_leader': List[object],
            'general_council': List[object],
            'trustee': List[object],
            'age': List[int],
            'main_organ': List[object]
        }

        self.attribute_map = {
            'viaf_id': 'viafId',
            'leader_function': 'leaderFunction',
            'number_of_members': 'numberOfMembers',
            'art_patron': 'artPatron',
            'manager_season': 'managerSeason',
            'secretary_general': 'secretaryGeneral',
            'number_of_locations': 'numberOfLocations',
            'discipline': 'discipline',
            'legislative_period_name': 'legislativePeriodName',
            'type': 'type',
            'committee_in_legislature': 'committeeInLegislature',
            'revenue': 'revenue',
            'last_election_date': 'lastElectionDate',
            'affiliation': 'affiliation',
            'political_party_in_legislature': 'politicalPartyInLegislature',
            'meeting_city': 'meetingCity',
            'season': 'season',
            'meeting_building': 'meetingBuilding',
            'id': 'id',
            'nla_id': 'nlaId',
            'chairperson': 'chairperson',
            'region_served': 'regionServed',
            'superintendent': 'superintendent',
            'formation_date': 'formationDate',
            'number_of_employees': 'numberOfEmployees',
            'election_date_leader': 'electionDateLeader',
            'extinction_date': 'extinctionDate',
            'player_season': 'playerSeason',
            'endowment': 'endowment',
            'slogan': 'slogan',
            'regional_council': 'regionalCouncil',
            'location_city': 'locationCity',
            'number_of_volunteers': 'numberOfVolunteers',
            'ideology': 'ideology',
            'description': 'description',
            'membership': 'membership',
            'ceo': 'ceo',
            'house': 'house',
            'formation_year': 'formationYear',
            'junior_season': 'juniorSeason',
            'headquarter': 'headquarter',
            'extinction_year': 'extinctionYear',
            'child_organisation': 'childOrganisation',
            'honours': 'honours',
            'parent_organisation': 'parentOrganisation',
            'organisation_member': 'organisationMember',
            'number_of_staff': 'numberOfStaff',
            'product': 'product',
            'hometown': 'hometown',
            'foundation_place': 'foundationPlace',
            'national_selection': 'nationalSelection',
            'label': 'label',
            'legal_form': 'legalForm',
            'political_party_of_leader': 'politicalPartyOfLeader',
            'general_council': 'generalCouncil',
            'trustee': 'trustee',
            'age': 'age',
            'main_organ': 'mainOrgan'
        }

        self._viaf_id = viaf_id
        self._leader_function = leader_function
        self._number_of_members = number_of_members
        self._art_patron = art_patron
        self._manager_season = manager_season
        self._secretary_general = secretary_general
        self._number_of_locations = number_of_locations
        self._discipline = discipline
        self._legislative_period_name = legislative_period_name
        self._type = type
        self._committee_in_legislature = committee_in_legislature
        self._revenue = revenue
        self._last_election_date = last_election_date
        self._affiliation = affiliation
        self._political_party_in_legislature = political_party_in_legislature
        self._meeting_city = meeting_city
        self._season = season
        self._meeting_building = meeting_building
        self._id = id
        self._nla_id = nla_id
        self._chairperson = chairperson
        self._region_served = region_served
        self._superintendent = superintendent
        self._formation_date = formation_date
        self._number_of_employees = number_of_employees
        self._election_date_leader = election_date_leader
        self._extinction_date = extinction_date
        self._player_season = player_season
        self._endowment = endowment
        self._slogan = slogan
        self._regional_council = regional_council
        self._location_city = location_city
        self._number_of_volunteers = number_of_volunteers
        self._ideology = ideology
        self._description = description
        self._membership = membership
        self._ceo = ceo
        self._house = house
        self._formation_year = formation_year
        self._junior_season = junior_season
        self._headquarter = headquarter
        self._extinction_year = extinction_year
        self._child_organisation = child_organisation
        self._honours = honours
        self._parent_organisation = parent_organisation
        self._organisation_member = organisation_member
        self._number_of_staff = number_of_staff
        self._product = product
        self._hometown = hometown
        self._foundation_place = foundation_place
        self._national_selection = national_selection
        self._label = label
        self._legal_form = legal_form
        self._political_party_of_leader = political_party_of_leader
        self._general_council = general_council
        self._trustee = trustee
        self._age = age
        self._main_organ = main_organ

    @classmethod
    def from_dict(cls, dikt) -> 'Legislature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Legislature of this Legislature.  # noqa: E501
        :rtype: Legislature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def viaf_id(self):
        """Gets the viaf_id of this Legislature.

        International authority data from the Online Computer Library Center (OCLC)  # noqa: E501

        :return: The viaf_id of this Legislature.
        :rtype: List[str]
        """
        return self._viaf_id

    @viaf_id.setter
    def viaf_id(self, viaf_id):
        """Sets the viaf_id of this Legislature.

        International authority data from the Online Computer Library Center (OCLC)  # noqa: E501

        :param viaf_id: The viaf_id of this Legislature.
        :type viaf_id: List[str]
        """

        self._viaf_id = viaf_id

    @property
    def leader_function(self):
        """Gets the leader_function of this Legislature.

        Description not available  # noqa: E501

        :return: The leader_function of this Legislature.
        :rtype: List[object]
        """
        return self._leader_function

    @leader_function.setter
    def leader_function(self, leader_function):
        """Sets the leader_function of this Legislature.

        Description not available  # noqa: E501

        :param leader_function: The leader_function of this Legislature.
        :type leader_function: List[object]
        """

        self._leader_function = leader_function

    @property
    def number_of_members(self):
        """Gets the number_of_members of this Legislature.

        Description not available  # noqa: E501

        :return: The number_of_members of this Legislature.
        :rtype: List[int]
        """
        return self._number_of_members

    @number_of_members.setter
    def number_of_members(self, number_of_members):
        """Sets the number_of_members of this Legislature.

        Description not available  # noqa: E501

        :param number_of_members: The number_of_members of this Legislature.
        :type number_of_members: List[int]
        """

        self._number_of_members = number_of_members

    @property
    def art_patron(self):
        """Gets the art_patron of this Legislature.

        An influential, wealthy person who supported an artist, craftsman, a scholar or a noble.. See also  # noqa: E501

        :return: The art_patron of this Legislature.
        :rtype: List[object]
        """
        return self._art_patron

    @art_patron.setter
    def art_patron(self, art_patron):
        """Sets the art_patron of this Legislature.

        An influential, wealthy person who supported an artist, craftsman, a scholar or a noble.. See also  # noqa: E501

        :param art_patron: The art_patron of this Legislature.
        :type art_patron: List[object]
        """

        self._art_patron = art_patron

    @property
    def manager_season(self):
        """Gets the manager_season of this Legislature.

        Description not available  # noqa: E501

        :return: The manager_season of this Legislature.
        :rtype: List[object]
        """
        return self._manager_season

    @manager_season.setter
    def manager_season(self, manager_season):
        """Sets the manager_season of this Legislature.

        Description not available  # noqa: E501

        :param manager_season: The manager_season of this Legislature.
        :type manager_season: List[object]
        """

        self._manager_season = manager_season

    @property
    def secretary_general(self):
        """Gets the secretary_general of this Legislature.

        Description not available  # noqa: E501

        :return: The secretary_general of this Legislature.
        :rtype: List[object]
        """
        return self._secretary_general

    @secretary_general.setter
    def secretary_general(self, secretary_general):
        """Sets the secretary_general of this Legislature.

        Description not available  # noqa: E501

        :param secretary_general: The secretary_general of this Legislature.
        :type secretary_general: List[object]
        """

        self._secretary_general = secretary_general

    @property
    def number_of_locations(self):
        """Gets the number_of_locations of this Legislature.

        Description not available  # noqa: E501

        :return: The number_of_locations of this Legislature.
        :rtype: List[int]
        """
        return self._number_of_locations

    @number_of_locations.setter
    def number_of_locations(self, number_of_locations):
        """Sets the number_of_locations of this Legislature.

        Description not available  # noqa: E501

        :param number_of_locations: The number_of_locations of this Legislature.
        :type number_of_locations: List[int]
        """

        self._number_of_locations = number_of_locations

    @property
    def discipline(self):
        """Gets the discipline of this Legislature.

        Description not available  # noqa: E501

        :return: The discipline of this Legislature.
        :rtype: List[object]
        """
        return self._discipline

    @discipline.setter
    def discipline(self, discipline):
        """Sets the discipline of this Legislature.

        Description not available  # noqa: E501

        :param discipline: The discipline of this Legislature.
        :type discipline: List[object]
        """

        self._discipline = discipline

    @property
    def legislative_period_name(self):
        """Gets the legislative_period_name of this Legislature.

        The term of the on-going session (e.g.: \"40th Canadian Parliament\").  # noqa: E501

        :return: The legislative_period_name of this Legislature.
        :rtype: List[str]
        """
        return self._legislative_period_name

    @legislative_period_name.setter
    def legislative_period_name(self, legislative_period_name):
        """Sets the legislative_period_name of this Legislature.

        The term of the on-going session (e.g.: \"40th Canadian Parliament\").  # noqa: E501

        :param legislative_period_name: The legislative_period_name of this Legislature.
        :type legislative_period_name: List[str]
        """

        self._legislative_period_name = legislative_period_name

    @property
    def type(self):
        """Gets the type of this Legislature.

        type of the resource  # noqa: E501

        :return: The type of this Legislature.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Legislature.

        type of the resource  # noqa: E501

        :param type: The type of this Legislature.
        :type type: List[str]
        """

        self._type = type

    @property
    def committee_in_legislature(self):
        """Gets the committee_in_legislature of this Legislature.

        Committee in the legislature (eg.: Committee on Economic and Monetary Affairs of the European Parliament).  # noqa: E501

        :return: The committee_in_legislature of this Legislature.
        :rtype: List[object]
        """
        return self._committee_in_legislature

    @committee_in_legislature.setter
    def committee_in_legislature(self, committee_in_legislature):
        """Sets the committee_in_legislature of this Legislature.

        Committee in the legislature (eg.: Committee on Economic and Monetary Affairs of the European Parliament).  # noqa: E501

        :param committee_in_legislature: The committee_in_legislature of this Legislature.
        :type committee_in_legislature: List[object]
        """

        self._committee_in_legislature = committee_in_legislature

    @property
    def revenue(self):
        """Gets the revenue of this Legislature.

        Description not available  # noqa: E501

        :return: The revenue of this Legislature.
        :rtype: List[float]
        """
        return self._revenue

    @revenue.setter
    def revenue(self, revenue):
        """Sets the revenue of this Legislature.

        Description not available  # noqa: E501

        :param revenue: The revenue of this Legislature.
        :type revenue: List[float]
        """

        self._revenue = revenue

    @property
    def last_election_date(self):
        """Gets the last_election_date of this Legislature.

        The last election date for the house.  # noqa: E501

        :return: The last_election_date of this Legislature.
        :rtype: List[str]
        """
        return self._last_election_date

    @last_election_date.setter
    def last_election_date(self, last_election_date):
        """Sets the last_election_date of this Legislature.

        The last election date for the house.  # noqa: E501

        :param last_election_date: The last_election_date of this Legislature.
        :type last_election_date: List[str]
        """

        self._last_election_date = last_election_date

    @property
    def affiliation(self):
        """Gets the affiliation of this Legislature.

        Description not available  # noqa: E501

        :return: The affiliation of this Legislature.
        :rtype: List[object]
        """
        return self._affiliation

    @affiliation.setter
    def affiliation(self, affiliation):
        """Sets the affiliation of this Legislature.

        Description not available  # noqa: E501

        :param affiliation: The affiliation of this Legislature.
        :type affiliation: List[object]
        """

        self._affiliation = affiliation

    @property
    def political_party_in_legislature(self):
        """Gets the political_party_in_legislature of this Legislature.

        Political party in the legislature (eg.: European People's Party in the European Parliament).  # noqa: E501

        :return: The political_party_in_legislature of this Legislature.
        :rtype: List[object]
        """
        return self._political_party_in_legislature

    @political_party_in_legislature.setter
    def political_party_in_legislature(self, political_party_in_legislature):
        """Sets the political_party_in_legislature of this Legislature.

        Political party in the legislature (eg.: European People's Party in the European Parliament).  # noqa: E501

        :param political_party_in_legislature: The political_party_in_legislature of this Legislature.
        :type political_party_in_legislature: List[object]
        """

        self._political_party_in_legislature = political_party_in_legislature

    @property
    def meeting_city(self):
        """Gets the meeting_city of this Legislature.

        Description not available  # noqa: E501

        :return: The meeting_city of this Legislature.
        :rtype: List[object]
        """
        return self._meeting_city

    @meeting_city.setter
    def meeting_city(self, meeting_city):
        """Sets the meeting_city of this Legislature.

        Description not available  # noqa: E501

        :param meeting_city: The meeting_city of this Legislature.
        :type meeting_city: List[object]
        """

        self._meeting_city = meeting_city

    @property
    def season(self):
        """Gets the season of this Legislature.

        Description not available  # noqa: E501

        :return: The season of this Legislature.
        :rtype: List[object]
        """
        return self._season

    @season.setter
    def season(self, season):
        """Sets the season of this Legislature.

        Description not available  # noqa: E501

        :param season: The season of this Legislature.
        :type season: List[object]
        """

        self._season = season

    @property
    def meeting_building(self):
        """Gets the meeting_building of this Legislature.

        Description not available  # noqa: E501

        :return: The meeting_building of this Legislature.
        :rtype: List[object]
        """
        return self._meeting_building

    @meeting_building.setter
    def meeting_building(self, meeting_building):
        """Sets the meeting_building of this Legislature.

        Description not available  # noqa: E501

        :param meeting_building: The meeting_building of this Legislature.
        :type meeting_building: List[object]
        """

        self._meeting_building = meeting_building

    @property
    def id(self):
        """Gets the id of this Legislature.

        identifier  # noqa: E501

        :return: The id of this Legislature.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Legislature.

        identifier  # noqa: E501

        :param id: The id of this Legislature.
        :type id: str
        """

        self._id = id

    @property
    def nla_id(self):
        """Gets the nla_id of this Legislature.

        NLA Trove’s People and Organisation view allows the discovery of biographical and other contextual information about people and organisations. Search also available via VIAF.  # noqa: E501

        :return: The nla_id of this Legislature.
        :rtype: List[str]
        """
        return self._nla_id

    @nla_id.setter
    def nla_id(self, nla_id):
        """Sets the nla_id of this Legislature.

        NLA Trove’s People and Organisation view allows the discovery of biographical and other contextual information about people and organisations. Search also available via VIAF.  # noqa: E501

        :param nla_id: The nla_id of this Legislature.
        :type nla_id: List[str]
        """

        self._nla_id = nla_id

    @property
    def chairperson(self):
        """Gets the chairperson of this Legislature.

        Description not available  # noqa: E501

        :return: The chairperson of this Legislature.
        :rtype: List[object]
        """
        return self._chairperson

    @chairperson.setter
    def chairperson(self, chairperson):
        """Sets the chairperson of this Legislature.

        Description not available  # noqa: E501

        :param chairperson: The chairperson of this Legislature.
        :type chairperson: List[object]
        """

        self._chairperson = chairperson

    @property
    def region_served(self):
        """Gets the region_served of this Legislature.

        Description not available  # noqa: E501

        :return: The region_served of this Legislature.
        :rtype: List[object]
        """
        return self._region_served

    @region_served.setter
    def region_served(self, region_served):
        """Sets the region_served of this Legislature.

        Description not available  # noqa: E501

        :param region_served: The region_served of this Legislature.
        :type region_served: List[object]
        """

        self._region_served = region_served

    @property
    def superintendent(self):
        """Gets the superintendent of this Legislature.

        Description not available  # noqa: E501

        :return: The superintendent of this Legislature.
        :rtype: List[object]
        """
        return self._superintendent

    @superintendent.setter
    def superintendent(self, superintendent):
        """Sets the superintendent of this Legislature.

        Description not available  # noqa: E501

        :param superintendent: The superintendent of this Legislature.
        :type superintendent: List[object]
        """

        self._superintendent = superintendent

    @property
    def formation_date(self):
        """Gets the formation_date of this Legislature.

        Description not available  # noqa: E501

        :return: The formation_date of this Legislature.
        :rtype: List[str]
        """
        return self._formation_date

    @formation_date.setter
    def formation_date(self, formation_date):
        """Sets the formation_date of this Legislature.

        Description not available  # noqa: E501

        :param formation_date: The formation_date of this Legislature.
        :type formation_date: List[str]
        """

        self._formation_date = formation_date

    @property
    def number_of_employees(self):
        """Gets the number_of_employees of this Legislature.

        Description not available  # noqa: E501

        :return: The number_of_employees of this Legislature.
        :rtype: List[int]
        """
        return self._number_of_employees

    @number_of_employees.setter
    def number_of_employees(self, number_of_employees):
        """Sets the number_of_employees of this Legislature.

        Description not available  # noqa: E501

        :param number_of_employees: The number_of_employees of this Legislature.
        :type number_of_employees: List[int]
        """

        self._number_of_employees = number_of_employees

    @property
    def election_date_leader(self):
        """Gets the election_date_leader of this Legislature.

        The date that leader was elected.  # noqa: E501

        :return: The election_date_leader of this Legislature.
        :rtype: List[str]
        """
        return self._election_date_leader

    @election_date_leader.setter
    def election_date_leader(self, election_date_leader):
        """Sets the election_date_leader of this Legislature.

        The date that leader was elected.  # noqa: E501

        :param election_date_leader: The election_date_leader of this Legislature.
        :type election_date_leader: List[str]
        """

        self._election_date_leader = election_date_leader

    @property
    def extinction_date(self):
        """Gets the extinction_date of this Legislature.

        Description not available  # noqa: E501

        :return: The extinction_date of this Legislature.
        :rtype: List[str]
        """
        return self._extinction_date

    @extinction_date.setter
    def extinction_date(self, extinction_date):
        """Sets the extinction_date of this Legislature.

        Description not available  # noqa: E501

        :param extinction_date: The extinction_date of this Legislature.
        :type extinction_date: List[str]
        """

        self._extinction_date = extinction_date

    @property
    def player_season(self):
        """Gets the player_season of this Legislature.

        Description not available  # noqa: E501

        :return: The player_season of this Legislature.
        :rtype: List[object]
        """
        return self._player_season

    @player_season.setter
    def player_season(self, player_season):
        """Sets the player_season of this Legislature.

        Description not available  # noqa: E501

        :param player_season: The player_season of this Legislature.
        :type player_season: List[object]
        """

        self._player_season = player_season

    @property
    def endowment(self):
        """Gets the endowment of this Legislature.

        Description not available  # noqa: E501

        :return: The endowment of this Legislature.
        :rtype: List[float]
        """
        return self._endowment

    @endowment.setter
    def endowment(self, endowment):
        """Sets the endowment of this Legislature.

        Description not available  # noqa: E501

        :param endowment: The endowment of this Legislature.
        :type endowment: List[float]
        """

        self._endowment = endowment

    @property
    def slogan(self):
        """Gets the slogan of this Legislature.

        Description not available  # noqa: E501

        :return: The slogan of this Legislature.
        :rtype: List[str]
        """
        return self._slogan

    @slogan.setter
    def slogan(self, slogan):
        """Sets the slogan of this Legislature.

        Description not available  # noqa: E501

        :param slogan: The slogan of this Legislature.
        :type slogan: List[str]
        """

        self._slogan = slogan

    @property
    def regional_council(self):
        """Gets the regional_council of this Legislature.

        Description not available  # noqa: E501

        :return: The regional_council of this Legislature.
        :rtype: List[object]
        """
        return self._regional_council

    @regional_council.setter
    def regional_council(self, regional_council):
        """Sets the regional_council of this Legislature.

        Description not available  # noqa: E501

        :param regional_council: The regional_council of this Legislature.
        :type regional_council: List[object]
        """

        self._regional_council = regional_council

    @property
    def location_city(self):
        """Gets the location_city of this Legislature.

        City the thing is located.  # noqa: E501

        :return: The location_city of this Legislature.
        :rtype: List[object]
        """
        return self._location_city

    @location_city.setter
    def location_city(self, location_city):
        """Sets the location_city of this Legislature.

        City the thing is located.  # noqa: E501

        :param location_city: The location_city of this Legislature.
        :type location_city: List[object]
        """

        self._location_city = location_city

    @property
    def number_of_volunteers(self):
        """Gets the number_of_volunteers of this Legislature.

        Description not available  # noqa: E501

        :return: The number_of_volunteers of this Legislature.
        :rtype: List[int]
        """
        return self._number_of_volunteers

    @number_of_volunteers.setter
    def number_of_volunteers(self, number_of_volunteers):
        """Sets the number_of_volunteers of this Legislature.

        Description not available  # noqa: E501

        :param number_of_volunteers: The number_of_volunteers of this Legislature.
        :type number_of_volunteers: List[int]
        """

        self._number_of_volunteers = number_of_volunteers

    @property
    def ideology(self):
        """Gets the ideology of this Legislature.

        Description not available  # noqa: E501

        :return: The ideology of this Legislature.
        :rtype: List[object]
        """
        return self._ideology

    @ideology.setter
    def ideology(self, ideology):
        """Sets the ideology of this Legislature.

        Description not available  # noqa: E501

        :param ideology: The ideology of this Legislature.
        :type ideology: List[object]
        """

        self._ideology = ideology

    @property
    def description(self):
        """Gets the description of this Legislature.

        small description  # noqa: E501

        :return: The description of this Legislature.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Legislature.

        small description  # noqa: E501

        :param description: The description of this Legislature.
        :type description: List[str]
        """

        self._description = description

    @property
    def membership(self):
        """Gets the membership of this Legislature.

        Description not available  # noqa: E501

        :return: The membership of this Legislature.
        :rtype: List[str]
        """
        return self._membership

    @membership.setter
    def membership(self, membership):
        """Sets the membership of this Legislature.

        Description not available  # noqa: E501

        :param membership: The membership of this Legislature.
        :type membership: List[str]
        """

        self._membership = membership

    @property
    def ceo(self):
        """Gets the ceo of this Legislature.

        Description not available  # noqa: E501

        :return: The ceo of this Legislature.
        :rtype: List[object]
        """
        return self._ceo

    @ceo.setter
    def ceo(self, ceo):
        """Sets the ceo of this Legislature.

        Description not available  # noqa: E501

        :param ceo: The ceo of this Legislature.
        :type ceo: List[object]
        """

        self._ceo = ceo

    @property
    def house(self):
        """Gets the house of this Legislature.

        Description not available  # noqa: E501

        :return: The house of this Legislature.
        :rtype: List[object]
        """
        return self._house

    @house.setter
    def house(self, house):
        """Sets the house of this Legislature.

        Description not available  # noqa: E501

        :param house: The house of this Legislature.
        :type house: List[object]
        """

        self._house = house

    @property
    def formation_year(self):
        """Gets the formation_year of this Legislature.

        Description not available  # noqa: E501

        :return: The formation_year of this Legislature.
        :rtype: List[str]
        """
        return self._formation_year

    @formation_year.setter
    def formation_year(self, formation_year):
        """Sets the formation_year of this Legislature.

        Description not available  # noqa: E501

        :param formation_year: The formation_year of this Legislature.
        :type formation_year: List[str]
        """

        self._formation_year = formation_year

    @property
    def junior_season(self):
        """Gets the junior_season of this Legislature.

        Description not available  # noqa: E501

        :return: The junior_season of this Legislature.
        :rtype: List[object]
        """
        return self._junior_season

    @junior_season.setter
    def junior_season(self, junior_season):
        """Sets the junior_season of this Legislature.

        Description not available  # noqa: E501

        :param junior_season: The junior_season of this Legislature.
        :type junior_season: List[object]
        """

        self._junior_season = junior_season

    @property
    def headquarter(self):
        """Gets the headquarter of this Legislature.

        Description not available  # noqa: E501

        :return: The headquarter of this Legislature.
        :rtype: List[object]
        """
        return self._headquarter

    @headquarter.setter
    def headquarter(self, headquarter):
        """Sets the headquarter of this Legislature.

        Description not available  # noqa: E501

        :param headquarter: The headquarter of this Legislature.
        :type headquarter: List[object]
        """

        self._headquarter = headquarter

    @property
    def extinction_year(self):
        """Gets the extinction_year of this Legislature.

        Description not available  # noqa: E501

        :return: The extinction_year of this Legislature.
        :rtype: List[str]
        """
        return self._extinction_year

    @extinction_year.setter
    def extinction_year(self, extinction_year):
        """Sets the extinction_year of this Legislature.

        Description not available  # noqa: E501

        :param extinction_year: The extinction_year of this Legislature.
        :type extinction_year: List[str]
        """

        self._extinction_year = extinction_year

    @property
    def child_organisation(self):
        """Gets the child_organisation of this Legislature.

        Description not available  # noqa: E501

        :return: The child_organisation of this Legislature.
        :rtype: List[object]
        """
        return self._child_organisation

    @child_organisation.setter
    def child_organisation(self, child_organisation):
        """Sets the child_organisation of this Legislature.

        Description not available  # noqa: E501

        :param child_organisation: The child_organisation of this Legislature.
        :type child_organisation: List[object]
        """

        self._child_organisation = child_organisation

    @property
    def honours(self):
        """Gets the honours of this Legislature.

        Description not available  # noqa: E501

        :return: The honours of this Legislature.
        :rtype: List[object]
        """
        return self._honours

    @honours.setter
    def honours(self, honours):
        """Sets the honours of this Legislature.

        Description not available  # noqa: E501

        :param honours: The honours of this Legislature.
        :type honours: List[object]
        """

        self._honours = honours

    @property
    def parent_organisation(self):
        """Gets the parent_organisation of this Legislature.

        Description not available  # noqa: E501

        :return: The parent_organisation of this Legislature.
        :rtype: List[object]
        """
        return self._parent_organisation

    @parent_organisation.setter
    def parent_organisation(self, parent_organisation):
        """Sets the parent_organisation of this Legislature.

        Description not available  # noqa: E501

        :param parent_organisation: The parent_organisation of this Legislature.
        :type parent_organisation: List[object]
        """

        self._parent_organisation = parent_organisation

    @property
    def organisation_member(self):
        """Gets the organisation_member of this Legislature.

        Identify the members of an organisation.  # noqa: E501

        :return: The organisation_member of this Legislature.
        :rtype: List[object]
        """
        return self._organisation_member

    @organisation_member.setter
    def organisation_member(self, organisation_member):
        """Sets the organisation_member of this Legislature.

        Identify the members of an organisation.  # noqa: E501

        :param organisation_member: The organisation_member of this Legislature.
        :type organisation_member: List[object]
        """

        self._organisation_member = organisation_member

    @property
    def number_of_staff(self):
        """Gets the number_of_staff of this Legislature.

        Description not available  # noqa: E501

        :return: The number_of_staff of this Legislature.
        :rtype: List[int]
        """
        return self._number_of_staff

    @number_of_staff.setter
    def number_of_staff(self, number_of_staff):
        """Sets the number_of_staff of this Legislature.

        Description not available  # noqa: E501

        :param number_of_staff: The number_of_staff of this Legislature.
        :type number_of_staff: List[int]
        """

        self._number_of_staff = number_of_staff

    @property
    def product(self):
        """Gets the product of this Legislature.

        Description not available  # noqa: E501

        :return: The product of this Legislature.
        :rtype: List[object]
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this Legislature.

        Description not available  # noqa: E501

        :param product: The product of this Legislature.
        :type product: List[object]
        """

        self._product = product

    @property
    def hometown(self):
        """Gets the hometown of this Legislature.

        Description not available  # noqa: E501

        :return: The hometown of this Legislature.
        :rtype: List[object]
        """
        return self._hometown

    @hometown.setter
    def hometown(self, hometown):
        """Sets the hometown of this Legislature.

        Description not available  # noqa: E501

        :param hometown: The hometown of this Legislature.
        :type hometown: List[object]
        """

        self._hometown = hometown

    @property
    def foundation_place(self):
        """Gets the foundation_place of this Legislature.

        Description not available  # noqa: E501

        :return: The foundation_place of this Legislature.
        :rtype: List[object]
        """
        return self._foundation_place

    @foundation_place.setter
    def foundation_place(self, foundation_place):
        """Sets the foundation_place of this Legislature.

        Description not available  # noqa: E501

        :param foundation_place: The foundation_place of this Legislature.
        :type foundation_place: List[object]
        """

        self._foundation_place = foundation_place

    @property
    def national_selection(self):
        """Gets the national_selection of this Legislature.

        Description not available  # noqa: E501

        :return: The national_selection of this Legislature.
        :rtype: List[object]
        """
        return self._national_selection

    @national_selection.setter
    def national_selection(self, national_selection):
        """Sets the national_selection of this Legislature.

        Description not available  # noqa: E501

        :param national_selection: The national_selection of this Legislature.
        :type national_selection: List[object]
        """

        self._national_selection = national_selection

    @property
    def label(self):
        """Gets the label of this Legislature.

        short description of the resource  # noqa: E501

        :return: The label of this Legislature.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Legislature.

        short description of the resource  # noqa: E501

        :param label: The label of this Legislature.
        :type label: List[str]
        """

        self._label = label

    @property
    def legal_form(self):
        """Gets the legal_form of this Legislature.

        There are many types of business entity defined in the legal systems of various countries. These include corporations, cooperatives, partnerships, sole traders, limited liability company and other specialized types of organization.  # noqa: E501

        :return: The legal_form of this Legislature.
        :rtype: List[object]
        """
        return self._legal_form

    @legal_form.setter
    def legal_form(self, legal_form):
        """Sets the legal_form of this Legislature.

        There are many types of business entity defined in the legal systems of various countries. These include corporations, cooperatives, partnerships, sole traders, limited liability company and other specialized types of organization.  # noqa: E501

        :param legal_form: The legal_form of this Legislature.
        :type legal_form: List[object]
        """

        self._legal_form = legal_form

    @property
    def political_party_of_leader(self):
        """Gets the political_party_of_leader of this Legislature.

        The Political party of leader.  # noqa: E501

        :return: The political_party_of_leader of this Legislature.
        :rtype: List[object]
        """
        return self._political_party_of_leader

    @political_party_of_leader.setter
    def political_party_of_leader(self, political_party_of_leader):
        """Sets the political_party_of_leader of this Legislature.

        The Political party of leader.  # noqa: E501

        :param political_party_of_leader: The political_party_of_leader of this Legislature.
        :type political_party_of_leader: List[object]
        """

        self._political_party_of_leader = political_party_of_leader

    @property
    def general_council(self):
        """Gets the general_council of this Legislature.

        Description not available  # noqa: E501

        :return: The general_council of this Legislature.
        :rtype: List[object]
        """
        return self._general_council

    @general_council.setter
    def general_council(self, general_council):
        """Sets the general_council of this Legislature.

        Description not available  # noqa: E501

        :param general_council: The general_council of this Legislature.
        :type general_council: List[object]
        """

        self._general_council = general_council

    @property
    def trustee(self):
        """Gets the trustee of this Legislature.

        Description not available  # noqa: E501

        :return: The trustee of this Legislature.
        :rtype: List[object]
        """
        return self._trustee

    @trustee.setter
    def trustee(self, trustee):
        """Sets the trustee of this Legislature.

        Description not available  # noqa: E501

        :param trustee: The trustee of this Legislature.
        :type trustee: List[object]
        """

        self._trustee = trustee

    @property
    def age(self):
        """Gets the age of this Legislature.

        Description not available  # noqa: E501

        :return: The age of this Legislature.
        :rtype: List[int]
        """
        return self._age

    @age.setter
    def age(self, age):
        """Sets the age of this Legislature.

        Description not available  # noqa: E501

        :param age: The age of this Legislature.
        :type age: List[int]
        """

        self._age = age

    @property
    def main_organ(self):
        """Gets the main_organ of this Legislature.

        Description not available  # noqa: E501

        :return: The main_organ of this Legislature.
        :rtype: List[object]
        """
        return self._main_organ

    @main_organ.setter
    def main_organ(self, main_organ):
        """Sets the main_organ of this Legislature.

        Description not available  # noqa: E501

        :param main_organ: The main_organ of this Legislature.
        :type main_organ: List[object]
        """

        self._main_organ = main_organ
