# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Monastry(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, description=None, religious_order=None, id=None, label=None, type=None):  # noqa: E501
        """Monastry - a model defined in OpenAPI

        :param description: The description of this Monastry.  # noqa: E501
        :type description: List[str]
        :param religious_order: The religious_order of this Monastry.  # noqa: E501
        :type religious_order: List[object]
        :param id: The id of this Monastry.  # noqa: E501
        :type id: str
        :param label: The label of this Monastry.  # noqa: E501
        :type label: List[str]
        :param type: The type of this Monastry.  # noqa: E501
        :type type: List[str]
        """


        self.openapi_types = {
            'description': List[str],
            'religious_order': List[object],
            'id': str,
            'label': List[str],
            'type': List[str]
        }

        self.attribute_map = {
            'description': 'description',
            'religious_order': 'religiousOrder',
            'id': 'id',
            'label': 'label',
            'type': 'type'
        }

        self._description = description
        self._religious_order = religious_order
        self._id = id
        self._label = label
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Monastry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Monastry of this Monastry.  # noqa: E501
        :rtype: Monastry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self):
        """Gets the description of this Monastry.

        small description  # noqa: E501

        :return: The description of this Monastry.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Monastry.

        small description  # noqa: E501

        :param description: The description of this Monastry.
        :type description: List[str]
        """

        self._description = description

    @property
    def religious_order(self):
        """Gets the religious_order of this Monastry.

        Description not available  # noqa: E501

        :return: The religious_order of this Monastry.
        :rtype: List[object]
        """
        return self._religious_order

    @religious_order.setter
    def religious_order(self, religious_order):
        """Sets the religious_order of this Monastry.

        Description not available  # noqa: E501

        :param religious_order: The religious_order of this Monastry.
        :type religious_order: List[object]
        """

        self._religious_order = religious_order

    @property
    def id(self):
        """Gets the id of this Monastry.

        identifier  # noqa: E501

        :return: The id of this Monastry.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Monastry.

        identifier  # noqa: E501

        :param id: The id of this Monastry.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this Monastry.

        short description of the resource  # noqa: E501

        :return: The label of this Monastry.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Monastry.

        short description of the resource  # noqa: E501

        :param label: The label of this Monastry.
        :type label: List[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this Monastry.

        type of the resource  # noqa: E501

        :return: The type of this Monastry.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Monastry.

        type of the resource  # noqa: E501

        :param type: The type of this Monastry.
        :type type: List[str]
        """

        self._type = type
