# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NorwaySettlement(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, most_down_point=None, landskap=None, center=None, description=None, id=None, label=None, type=None):  # noqa: E501
        """NorwaySettlement - a model defined in OpenAPI

        :param most_down_point: The most_down_point of this NorwaySettlement.  # noqa: E501
        :type most_down_point: List[object]
        :param landskap: The landskap of this NorwaySettlement.  # noqa: E501
        :type landskap: List[str]
        :param center: The center of this NorwaySettlement.  # noqa: E501
        :type center: List[str]
        :param description: The description of this NorwaySettlement.  # noqa: E501
        :type description: List[str]
        :param id: The id of this NorwaySettlement.  # noqa: E501
        :type id: str
        :param label: The label of this NorwaySettlement.  # noqa: E501
        :type label: List[str]
        :param type: The type of this NorwaySettlement.  # noqa: E501
        :type type: List[str]
        """


        self.openapi_types = {
            'most_down_point': List[object],
            'landskap': List[str],
            'center': List[str],
            'description': List[str],
            'id': str,
            'label': List[str],
            'type': List[str]
        }

        self.attribute_map = {
            'most_down_point': 'mostDownPoint',
            'landskap': 'landskap',
            'center': 'center',
            'description': 'description',
            'id': 'id',
            'label': 'label',
            'type': 'type'
        }

        self._most_down_point = most_down_point
        self._landskap = landskap
        self._center = center
        self._description = description
        self._id = id
        self._label = label
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'NorwaySettlement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NorwaySettlement of this NorwaySettlement.  # noqa: E501
        :rtype: NorwaySettlement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def most_down_point(self):
        """Gets the most_down_point of this NorwaySettlement.

        Description not available  # noqa: E501

        :return: The most_down_point of this NorwaySettlement.
        :rtype: List[object]
        """
        return self._most_down_point

    @most_down_point.setter
    def most_down_point(self, most_down_point):
        """Sets the most_down_point of this NorwaySettlement.

        Description not available  # noqa: E501

        :param most_down_point: The most_down_point of this NorwaySettlement.
        :type most_down_point: List[object]
        """

        self._most_down_point = most_down_point

    @property
    def landskap(self):
        """Gets the landskap of this NorwaySettlement.

        Description not available  # noqa: E501

        :return: The landskap of this NorwaySettlement.
        :rtype: List[str]
        """
        return self._landskap

    @landskap.setter
    def landskap(self, landskap):
        """Sets the landskap of this NorwaySettlement.

        Description not available  # noqa: E501

        :param landskap: The landskap of this NorwaySettlement.
        :type landskap: List[str]
        """

        self._landskap = landskap

    @property
    def center(self):
        """Gets the center of this NorwaySettlement.

        Description not available  # noqa: E501

        :return: The center of this NorwaySettlement.
        :rtype: List[str]
        """
        return self._center

    @center.setter
    def center(self, center):
        """Sets the center of this NorwaySettlement.

        Description not available  # noqa: E501

        :param center: The center of this NorwaySettlement.
        :type center: List[str]
        """

        self._center = center

    @property
    def description(self):
        """Gets the description of this NorwaySettlement.

        small description  # noqa: E501

        :return: The description of this NorwaySettlement.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NorwaySettlement.

        small description  # noqa: E501

        :param description: The description of this NorwaySettlement.
        :type description: List[str]
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this NorwaySettlement.

        identifier  # noqa: E501

        :return: The id of this NorwaySettlement.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NorwaySettlement.

        identifier  # noqa: E501

        :param id: The id of this NorwaySettlement.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this NorwaySettlement.

        short description of the resource  # noqa: E501

        :return: The label of this NorwaySettlement.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this NorwaySettlement.

        short description of the resource  # noqa: E501

        :param label: The label of this NorwaySettlement.
        :type label: List[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this NorwaySettlement.

        type of the resource  # noqa: E501

        :return: The type of this NorwaySettlement.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NorwaySettlement.

        type of the resource  # noqa: E501

        :param type: The type of this NorwaySettlement.
        :type type: List[str]
        """

        self._type = type
