# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RomaniaSettlement(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, prefect_mandate=None, description=None, authority_title=None, id=None, label=None, type=None):  # noqa: E501
        """RomaniaSettlement - a model defined in OpenAPI

        :param prefect_mandate: The prefect_mandate of this RomaniaSettlement.  # noqa: E501
        :type prefect_mandate: List[str]
        :param description: The description of this RomaniaSettlement.  # noqa: E501
        :type description: List[str]
        :param authority_title: The authority_title of this RomaniaSettlement.  # noqa: E501
        :type authority_title: List[str]
        :param id: The id of this RomaniaSettlement.  # noqa: E501
        :type id: str
        :param label: The label of this RomaniaSettlement.  # noqa: E501
        :type label: List[str]
        :param type: The type of this RomaniaSettlement.  # noqa: E501
        :type type: List[str]
        """


        self.openapi_types = {
            'prefect_mandate': List[str],
            'description': List[str],
            'authority_title': List[str],
            'id': str,
            'label': List[str],
            'type': List[str]
        }

        self.attribute_map = {
            'prefect_mandate': 'prefectMandate',
            'description': 'description',
            'authority_title': 'authorityTitle',
            'id': 'id',
            'label': 'label',
            'type': 'type'
        }

        self._prefect_mandate = prefect_mandate
        self._description = description
        self._authority_title = authority_title
        self._id = id
        self._label = label
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'RomaniaSettlement':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RomaniaSettlement of this RomaniaSettlement.  # noqa: E501
        :rtype: RomaniaSettlement
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prefect_mandate(self):
        """Gets the prefect_mandate of this RomaniaSettlement.

        Description not available  # noqa: E501

        :return: The prefect_mandate of this RomaniaSettlement.
        :rtype: List[str]
        """
        return self._prefect_mandate

    @prefect_mandate.setter
    def prefect_mandate(self, prefect_mandate):
        """Sets the prefect_mandate of this RomaniaSettlement.

        Description not available  # noqa: E501

        :param prefect_mandate: The prefect_mandate of this RomaniaSettlement.
        :type prefect_mandate: List[str]
        """

        self._prefect_mandate = prefect_mandate

    @property
    def description(self):
        """Gets the description of this RomaniaSettlement.

        small description  # noqa: E501

        :return: The description of this RomaniaSettlement.
        :rtype: List[str]
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this RomaniaSettlement.

        small description  # noqa: E501

        :param description: The description of this RomaniaSettlement.
        :type description: List[str]
        """

        self._description = description

    @property
    def authority_title(self):
        """Gets the authority_title of this RomaniaSettlement.

        Description not available  # noqa: E501

        :return: The authority_title of this RomaniaSettlement.
        :rtype: List[str]
        """
        return self._authority_title

    @authority_title.setter
    def authority_title(self, authority_title):
        """Sets the authority_title of this RomaniaSettlement.

        Description not available  # noqa: E501

        :param authority_title: The authority_title of this RomaniaSettlement.
        :type authority_title: List[str]
        """

        self._authority_title = authority_title

    @property
    def id(self):
        """Gets the id of this RomaniaSettlement.

        identifier  # noqa: E501

        :return: The id of this RomaniaSettlement.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RomaniaSettlement.

        identifier  # noqa: E501

        :param id: The id of this RomaniaSettlement.
        :type id: str
        """

        self._id = id

    @property
    def label(self):
        """Gets the label of this RomaniaSettlement.

        short description of the resource  # noqa: E501

        :return: The label of this RomaniaSettlement.
        :rtype: List[str]
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this RomaniaSettlement.

        short description of the resource  # noqa: E501

        :param label: The label of this RomaniaSettlement.
        :type label: List[str]
        """

        self._label = label

    @property
    def type(self):
        """Gets the type of this RomaniaSettlement.

        type of the resource  # noqa: E501

        :return: The type of this RomaniaSettlement.
        :rtype: List[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RomaniaSettlement.

        type of the resource  # noqa: E501

        :param type: The type of this RomaniaSettlement.
        :type type: List[str]
        """

        self._type = type
